### ISSUE TITLE
The count of the annotations in cluster annotation gets messed up

### ISSUE THREAD

**Issue by NSCabezon** [efremidze/Cluster#86]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

The clustering count gets messed up, the numbers change from one cluster to another but they sometimes don't get updated...

![img_4683](https://user-images.githubusercontent.com/563761/45545202-ef1abc00-b819-11e8-8db6-c5262c1d4183.PNG)
![img_4685](https://user-images.githubusercontent.com/563761/45545201-ef1abc00-b819-11e8-8a0c-eecc9e0b66a7.PNG)
![img_4620](https://user-images.githubusercontent.com/563761/45545200-ee822580-b819-11e8-9f96-d46197019089.jpeg)

### Environment

- **iOS Version**: iOS 12GM (but I've had this problem for a while, it's not a GM related bug)
- **Device(s)**: iPhone X

**Comment by enkh-amgalan** [comment]
I have same issues

**Comment by emiliogambone** [comment]
Same problem, i think they just don't get updated

**Comment by emiliogambone** [comment]
If I understand your problem, you can substitute the clustering count in the views with the value of annotation.annotations.count. But the problem persist

**Comment by efremidze** [comment]
Thanks, I'll take a look today.

**Comment by efremidze** [comment]
Can you provide your configuration?

**Comment by NSCabezon** [comment]
Here you go:

```
		clusterManager.cellSize = 50
		clusterManager.maxZoomLevel = 17
		clusterManager.minCountForClustering = 3
		
		clusterManager.clusterPosition = .nearCenter
```

**Comment by efremidze** [comment]
Check out the latest version (2.2.9). Let me know if it fixes the bug.

**Comment by NSCabezon** [comment]
Still having the issue :(

**Comment by efremidze** [comment]
I'll try to reproduce. Do you have any reproduction steps?

**Comment by NSCabezon** [comment]
It reproduces always, the number doesn't show the real annotation count... idk

**Comment by NSCabezon** [comment]
Cluster and not clustered... so I guess not...

**Comment by efremidze** [comment]
It appears to be an issue causing ur mixing images and count clusters. I'll look into a possible improvement.

**Comment by efremidze** [comment]
Can you check that the `annotation.annotations.count` is correct for the ClusterAnnotationView? It might be related to reusing the MKAnnotationView.

**Comment by efremidze** [comment]
Released [2.3.0](https://github.com/efremidze/Cluster/releases/tag/2.3.0). Let me know if you still see the bug.

**Comment by efremidze** [comment]
After investigating, I found out the annotations are getting modified when `shouldDistributeAnnotationsOnSameCoordinate` is set to `true`. I'm currently looking for a solution.

**Comment by efremidze** [comment]
I have addressed this issue in Release [2.5.0](https://github.com/efremidze/Cluster/releases/tag/2.5.0). Please check it out.

**Comment by efremidze** [comment]
I have addressed this issue in #107. Please check it out!

**Comment by efremidze** [comment]
I have addressed this issue in #107. Try it out and let me know if this is still an issue.

**Comment by efremidze** [comment]
I have addressed this issue in #107. Let me know if this is still an issue.

**Comment by sharedcare** [comment]
I still have this issue, I set `minCountForClustering` to 5. And the count of annotation does not show the correct number. When I select a clusterAnnotationView on the map, the following code is not executed. `if let cluster = view.annotation as? ClusterAnnotation { \\ my code here }`
